#! /bin/bash

DOCKER_NAME="gpt2" # username in container
CONTAINER_NAME=$USER"-gpt2" # name of container
SRC="/" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=4200274
DOCKER_GROUP_ID=4200274

