#! /bin/bash
source credentials

docker run \
  -d \
  --shm-size=10g \
  --memory=120g \
  --cpus=16 \
  --user ${DOCKER_USER_ID}:${DOCKER_GROUP_ID} \
  --name ${CONTAINER_NAME} \
  --rm -it --init \
  --gpus '"device=5"' \
  -v /home/e.serov/Chat25:/app \
  -p 7860:7860 \
  ${DOCKER_NAME} 

